apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app
  name: hello-deployment
  annotations:
    link.argocd.argoproj.io/external-link: https://hub.docker.com/repository/docker/yftacherzog/hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: hello-deployment
        image: clouduser/hello-app:v1
        imagePullPolicy: Always
